image: node:18

stages:
  - test
  - build
  - deploy

variables:
  GIT_DEPTH: 0

include:
  - .gitlab/test.yaml
  - .gitlab/build.yaml
  - .gitlab/containerize.yaml
  - .gitlab/rollout.yaml

.rules:test:
  interruptible: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "stable"'
      when: on_success      
    - when: never
    - changes:
        - 'apps/**/*'
        - 'libs/**/*'
        - .gitlab-ci.yml
        - .gitlab/*

.rules:build:
  interruptible: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never  
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "stable"'
      when: on_success
    - when: never

.rules:rollout:staging:
  interruptible: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success   
    - if: '$CI_COMMIT_BRANCH == "stable"'
      when: never         
    - when: never

.rules:rollout:production:
  interruptible: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "stable"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: never         
    - when: never

.cache:
  interruptible: true
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline